// Decks de Ordem & Caos — A Metamorfose (20 cartas cada)
// Cartas 1–12 (Ordem) e 1–11 (Caos) vêm do Livro de Regras / Manuais; as demais foram criadas para completar 20.

const ordem = [
  { nome: 'O Pai Samsa', tipo: 'Personagem', valor: '+3', argumente: 'a autoridade do pai mantém a família de pé quando Gregor deixa de ser o provedor.', narracao: 'O pai ergue-se com uma autoridade que Gregor nunca conhecera. A metamorfose revelou o poder que sempre existiu ali.' },
  { nome: 'Grete, a Cuidadora', tipo: 'Personagem', valor: '+3', argumente: 'o cuidado de Grete prova que a família ainda preserva laços humanos.', narracao: 'É Grete quem leva a comida, quem ainda tenta manter um laço. Enquanto ela age, há humanidade nessa casa.' },
  { nome: 'A Mãe Samsa', tipo: 'Personagem', valor: '+3', argumente: 'a mãe, mesmo abalada, é quem segura a casa e impede o colapso.', narracao: 'A mãe desmaia, chora, mas não abandona a casa. Ela é o colapso silencioso da família — e por isso ainda sustenta a Ordem.' },
  { nome: 'A Dívida da Família', tipo: 'Evento', valor: '+2', argumente: 'a dívida explica e justifica as escolhas da família, não a crueldade.', narracao: 'Gregor sabia da dívida. Seu corpo-inseto é o corpo do trabalhador que adoeceu de ser necessário — e a dívida segue sem ele.' },
  { nome: 'O Gerente da Firma', tipo: 'Personagem', valor: '+2', argumente: 'o mundo do trabalho impõe uma ordem mais forte que a metamorfose.', narracao: 'O gerente vem pessoalmente à porta. O mundo do trabalho não tolera ausências — e é mais real para a família do que a criatura no quarto.' },
  { nome: 'A Rotina Preservada', tipo: 'Evento', valor: '+2', argumente: 'manter a rotina é a forma que a família encontra de sobreviver ao absurdo.', narracao: 'Jantar na hora, conversas educadas, silêncio nos corredores. Enquanto a rotina existe, a metamorfose pode ser ignorada.' },
  { nome: 'As Contas em Dia', tipo: 'Evento', valor: '+2', argumente: 'a família se reorganiza financeiramente e mostra que consegue seguir em frente.', narracao: 'A família descobre que a dívida já está quase paga. O fardo que Gregor carregava já estava quase resolvido sem ele.' },
  { nome: 'A Esperança de Cura', tipo: 'Evento', valor: '+2', argumente: 'a esperança de que Gregor melhore mantém a família unida.', narracao: 'Enquanto há esperança de cura, há razão para manter Gregor vivo. A família se agarra a isso para não enfrentar a verdade.' },
  { nome: 'O Uniforme do Pai', tipo: 'Item', valor: '+2 / +3', argumente: 'o pai recupera seu papel e reequilibra a hierarquia da casa.', narracao: 'O pai veste o uniforme e redescobre o poder. A metamorfose de Gregor inverteu a hierarquia da casa.' },
  { nome: 'O Quarto Fechado', tipo: 'Cenário', valor: '+1', argumente: 'fechar a porta protege a normalidade da família.', narracao: 'A porta fechada é o acordo tácito: enquanto ninguém vê, ninguém precisa decidir. A normalidade sobrevive no corredor.' },
  { nome: 'Os Pensionistas Chegam', tipo: 'Evento', valor: '+1', argumente: 'a família se adapta e a vida continua apesar de tudo.', narracao: 'A família adapta a casa para os pensionistas. A vida segue — não porque Gregor melhorou, mas porque o mundo não espera por ele.' },
  { nome: 'O Passeio de Primavera', tipo: 'Evento Especial', valor: '+3', especial: true, argumente: 'o final mostra a família renascida e a estabilidade restaurada.', narracao: 'A família vai ao campo como se Gregor nunca tivesse existido. Kafka não chama isso de alívio — é a maior condenação da obra.' },
  { nome: 'O Trem das Cinco', tipo: 'Evento', valor: '+1', argumente: 'a disciplina do trabalho organiza a vida até de Gregor, mesmo transformado.', narracao: 'Recém-transformado, Gregor só pensa no trem que perdeu. A lógica do trabalho sobrevive até dentro do corpo de inseto.' },
  { nome: 'A Faxineira', tipo: 'Personagem', valor: '+2', argumente: 'o absurdo pode ser absorvido pela rotina e deixar de assustar.', narracao: 'A velha criada chama Gregor de "velho besouro" e segue o serviço. O absurdo vira rotina doméstica.' },
  { nome: 'Os Novos Empregos', tipo: 'Evento', valor: '+2', argumente: 'cada membro da família encontra seu papel e a casa se reergue.', narracao: 'O pai vira contínuo de banco, a mãe costura para fora, Grete vira vendedora. A família descobre que consegue viver sem Gregor.' },
  { nome: 'O Retrato do Tenente', tipo: 'Item', valor: '+1', argumente: 'a família preserva a memória e a identidade que dão sentido ao lar.', narracao: 'Na parede, Gregor de uniforme, sorriso despreocupado, mão na espada. A família guarda o filho que ela quer lembrar — não o que está no quarto.' },
  { nome: 'A Sala de Estar', tipo: 'Cenário', valor: '+1', argumente: 'os rituais domésticos mantêm a família unida.', narracao: 'A lâmpada acesa, o pai lendo o jornal em voz alta, a mãe costurando. O ritual da noite continua, com ou sem Gregor.' },
  { nome: 'Grete Floresce', tipo: 'Evento', valor: '+2', argumente: 'a família se renova e ganha um futuro.', narracao: 'No fim, os pais notam que Grete virou uma bela moça. Está na hora de lhe procurar um marido — a família se renova.' },
  { nome: 'O Pai Expulsa os Pensionistas', tipo: 'Evento', valor: '+2', argumente: 'o pai reafirma a autoridade e defende a honra da casa.', narracao: '‘Saiam imediatamente da minha casa!’ O pai reassume a autoridade sobre o lar diante de estranhos.' },
  { nome: 'As Três Cartas de Justificativa', tipo: 'Evento', valor: '+1', argumente: 'a vida volta à normalidade organizada pelo trabalho.', narracao: 'Depois da morte de Gregor, os três escrevem aos patrões pedindo um dia de folga. A vida volta a ser organizada pelo trabalho.' },
];

const caos = [
  { nome: 'Gregor-Inseto', tipo: 'Personagem', valor: '−3', argumente: 'a metamorfose revela como Gregor sempre foi tratado: como um instrumento.', narracao: 'Não é um pesadelo — é Gregor, que acordou como sempre acordou, mas desta vez o corpo diz a verdade que o trabalho ocultava.' },
  { nome: 'O Quarto Escuro', tipo: 'Cenário', valor: '−2', argumente: 'o isolamento de Gregor mostra a família se desfazendo por dentro.', narracao: 'O quarto vai sendo esvaziado, a mobília removida. O inseto cresce no vazio — e o vazio cresce na família.' },
  { nome: 'A Música de Grete', tipo: 'Evento', valor: '−2', argumente: 'Gregor é mais humano que a família que o rejeita.', narracao: 'A música atravessa a porta e Gregor rasteja para ouvir. Ele é mais humano do que qualquer membro da família que passou sem olhar.' },
  { nome: 'A Ferida da Maçã', tipo: 'Item', valor: '−2', argumente: 'a violência do pai destrói a ilusão de uma família unida.', narracao: 'A maçã apodrece dentro do inseto. É a violência do pai — mas prova que Gregor ainda sente. Ele não é apenas um inseto.' },
  { nome: 'O Abandono de Grete', tipo: 'Evento', valor: '−1', argumente: 'quando Grete desiste, fica claro que o amor da família era condicional.', narracao: 'Grete foi a última a acreditar. Quando ela desiste, o abandono é completo — e Kafka mostra como a família sempre foi transacional.' },
  { nome: '"Precisamos nos Livrar Disso"', tipo: 'Evento Especial', valor: '−3', especial: true, argumente: 'a família desumaniza Gregor e revela sua verdadeira face.', narracao: 'Grete usa o neutro: "isso", não "ele". É quando a família desumaniza Gregor — e Kafka mostra que foi assim desde o início.' },
  { nome: 'A Decisão Final de Gregor', tipo: 'Evento Especial', valor: '−3', especial: true, argumente: 'o sacrifício de Gregor expõe o egoísmo da família.', narracao: 'Gregor pensa na família com carinho e amor. A convicção de que precisa desaparecer é talvez ainda mais firme que a da irmã.' },
  { nome: 'Escalar o Teto', tipo: 'Evento', valor: '−2', argumente: 'o novo corpo liberta Gregor da prisão da vida antiga.', narracao: 'Gregor descobre o prazer de subir pelas paredes e pendurar-se no teto. O corpo novo tem uma liberdade que o antigo nunca teve.' },
  { nome: 'O Quarto Esvaziado', tipo: 'Cenário', valor: '−2', argumente: 'apagar as coisas de Gregor é apagar sua humanidade.', narracao: 'Tiram os móveis para que ele tenha espaço. Mas cada móvel que sai leva um pedaço da memória humana de Gregor.' },
  { nome: 'A Voz Perdida', tipo: 'Evento', valor: '−2', argumente: 'sem comunicação, a família não tem mais como se entender.', narracao: '‘Era uma voz de animal’, diz o gerente. Gregor entende tudo, mas ninguém o entende mais — a comunicação acabou.' },
  { nome: 'Os Restos e a Podridão', tipo: 'Item', valor: '−1', argumente: 'o descaso da família com Gregor revela seu abandono.', narracao: 'Gregor rejeita o leite e prefere queijo estragado e legumes podres. O corpo mudou — mas a família nem pergunta o que ele sente.' },
  { nome: 'O Despertar', tipo: 'Evento', valor: '−2', argumente: 'o absurdo invade a vida sem aviso e nenhuma ordem resiste a ele.', narracao: '‘Certa manhã, ao despertar de sonhos inquietos...’ Kafka não explica nada. O absurdo não precisa de causa para ser verdade.' },
  { nome: 'A Fuga do Gerente', tipo: 'Evento', valor: '−2', argumente: 'o trabalho descarta Gregor assim que ele deixa de ser útil.', narracao: 'O gerente recua, tateando o corrimão, e foge escada abaixo. O mundo do trabalho descarta Gregor no primeiro dia.' },
  { nome: 'A Bengala do Pai', tipo: 'Item', valor: '−2', argumente: 'a "ordem" da família se sustenta pela violência.', narracao: 'Com a bengala e o jornal, o pai empurra Gregor de volta ao quarto, ferido e sangrando. A autoridade da Ordem é pura violência.' },
  { nome: 'A Poeira nas Costas', tipo: 'Cenário', valor: '−1', argumente: 'o descaso vira hábito e mostra a família desistindo de Gregor.', narracao: 'Gregor anda coberto de pó, fiapos e restos de comida. Ninguém limpa mais o quarto — o descaso virou hábito.' },
  { nome: 'A Dama de Peles', tipo: 'Item', valor: '−2', argumente: 'Gregor luta para manter a humanidade que a família tenta apagar.', narracao: 'Gregor se agarra ao quadro da dama de peles. Não deixará que levem isso — o último laço com o homem que ele foi.' },
  { nome: 'Os Pensionistas Reclamam', tipo: 'Evento', valor: '−2', argumente: 'a metamorfose expõe a vergonha e a fragilidade da família.', narracao: 'Os pensionistas veem Gregor, cospem no chão e recusam pagar. A vergonha da família deixa de ser segredo.' },
  { nome: 'O Caixeiro-Viajante', tipo: 'Personagem', valor: '−2', argumente: 'Gregor já era desumanizado pelo trabalho antes de virar inseto.', narracao: 'Trens, refeições ruins, relações passageiras que nunca viram amizade. Gregor já vivia como inseto muito antes de acordar como um.' },
  { nome: 'A Porta que se Fecha', tipo: 'Evento', valor: '−2', argumente: 'a família abandona Gregor de vez, e a ordem só volta com a morte dele.', narracao: 'Mal Gregor volta ao quarto, a porta é trancada às pressas. "Finalmente!", grita Grete. Ele morre sozinho do outro lado.' },
  { nome: 'O Silêncio da Casa', tipo: 'Cenário', valor: '−1', argumente: 'o silêncio da família já é uma forma de enterrar Gregor em vida.', narracao: 'A família passa a sussurrar, fala de Gregor na terceira pessoa, evita o corredor. O silêncio é a primeira forma de enterro.' },
];

module.exports = { ordem, caos };
